# Generated by Django 5.0.1 on 2024-01-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_borrowedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='borrowed_date',
            new_name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='return_date',
        ),
    ]
